### ISSUE TITLE
_binary_src_main_libmain_so_start

### ISSUE THREAD

**Issue by jibanes** [jw910731/MemLoadProgram#1]
where do you define _binary_src_main_libmain_so_start and _binary_src_main_libmain_so_end?

**Comment by jibanes** [comment]
[-] dlopen(): /proc/31746/fd/3: file too short

**Comment by jw910731** [comment]
The symbol is defined in an object file that is auto generated when building. The compiled shared object `src/main/libmain.so` is  treated as a binary blob. Linker transform it into an object file which contain the binary data and the start, end, size information which is those magic variable `_binary_src_main_libmain_so_start` and `_binary_src_main_libmain_so_end`.

I also encountered the "file too short" bug. But I'm still figuring out the reason.

Keep in mind that this project uses `memfd_create`, which is a newer feature in linux kernel. Make sure you got a Linux kernel that is version 3.17 or higher

**Comment by jibanes** [comment]
What I meant to ask is that I don't see where you pass to the linker _binary_src_main_libmain_so_start and _binary_src_main_libmain_so_end in the makefile

**Comment by jw910731** [comment]
https://github.com/jw910731/MemLoadProgram/blob/72dc8fdd5104fba3733d3ee7aff1877399281bf5/Makefile#L16-L17
The `ld` invocation is at here. Which tell the linker to treat `src/main/libmain.so` as a binary blob and generate a object file with the binary data of .so file and  global symbol `_binary_src_main_libmain_so_start`, `_binary_src_main_libmain_so_end` .

**Comment by jw910731** [comment]
I think the commit would patch this issue. Closed
